name: publish

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: macos-13

    environment:
      name: production
      url: https://www.npmjs.com/package/@appdmg/macos-alias

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup node 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        registry-url: ${{ vars.NODE_REGISTRY_URL }}

    - name: setup python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: setup npm
      run: npm install -g npm@11

    - name: npm ci
      run: npm ci

    - name: npm publish
      run: npm publish --provenance --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_REGISTRY_TOKEN }}
